package pages;

import com.microsoft.playwright.*;

public class TradetronPage extends BasePage {
    private final String searchstring_input = "role=textbox[name=\"Search\"]";
    private final String latest = "role=checkbox[name=\"Latest\"]";
    private final String minfees = "role=checkbox[name=\"Min Fees\"]";
    private final String maxdeployment = "role=checkbox[name=\"Max Deployment\"]";
    private final String mincapital = "role=checkbox[name=\"Min Capital\"]";
    private final String algostrategy = "role=checkbox[name=\"Algo Strategy\"]";
    private final String stockbag_checkbox = "role=checkbox[name=\"Stock Bag\"]";
    private final String tags__ = "#tags[]";
    private final String exchanges__ = "#exchanges[]";
    private final String fixed_fee_free = "role=radio[name=\"Free\"]";
    private final String fixed_fee_paid = "role=radio[name=\"Paid\"]";
    private final String search_strategy_input = "role=textbox[name=\"Search strategy\"]";
    private final String email_input = "role=textbox[name=\"Email\"]";
    private final String password_input = "role=textbox[name=\"Password\"]";
    private final String altcha_checkbox_69299676 = "role=checkbox[name=\"I\'m not a robot\"]";
    private final String name = "role=textbox[name=\"Full Name\"]";
    private final String email_signup_input = "role=textbox[name=\"Email\"]";
    private final String phone_code = "#modalCountryCodeSignUp";
    private final String mobile = "role=textbox[name=\"Phone\"]";
    private final String country_id = "role=combobox[name=\"Country\"]";
    private final String state_id = "role=combobox[name=\"Select State\"]";
    private final String password_signup_input = "role=textbox[name=\"Password\"]";
    private final String terms_of_service_checkbox = "role=checkbox[name=\"I agree to the terms of service\"]";
    private final String altcha_checkbox_46869353 = "role=checkbox[name=\"I\'m not a robot\"]";
    private final String a = "role=link";
    private final String in = "role=button[name=\"IN\"]";
    private final String features_button = "role=button[name=\"Features\"]";
    private final String trading_engine = "role=link[name=\"Trading Engine\"]";
    private final String strategy_builder = "role=link[name=\"Strategy Builder\"]";
    private final String social_trading = "role=link[name=\"Social Trading\"]";
    private final String backtesting_engine = "role=link[name=\"Backtesting Engine\"]";
    private final String execution_algos = "role=link[name=\"Execution Algos\"]";
    private final String reports = "role=link[name=\"Reports\"]";
    private final String fund_management = "role=link[name=\"Fund Management\"]";
    private final String keywords = "role=link[name=\"Keywords\"]";
    private final String stock_bag = "role=link[name=\"Stock Bag\"]";
    private final String use_cases = "role=button[name=\"Use cases\"]";
    private final String strategy_creators = "role=link[name=\"Strategy Creators\"]";
    private final String investors = "role=link[name=\"Investors\"]";
    private final String brokers = "role=link[name=\"Brokers\"]";
    private final String services = "role=button[name=\"Services\"]";
    private final String tt_uni = "role=link[name=\"TT Uni\"]";
    private final String tt_quants = "role=link[name=\"TT Quants\"]";
    private final String tt_assistant = "role=link[name=\"TT Assistant\"]";
    private final String tt_strategycoded = "role=link[name=\"TT Strategycoded\"]";
    private final String tt_whitelabel = "role=link[name=\"TT Whitelabel\"]";
    private final String pricing = "role=link[name=\"Pricing\"]";
    private final String contact = "role=link[name=\"Contact\"]";
    private final String sign_up_link = "role=link[name=\"Sign up\"]";
    private final String sign_in_link = "role=link[name=\"Sign in\"]";
    private final String unlock_birthday_pric = "role=link[name=\"Unlock Birthday Pricing\"]";
    private final String close_link = "role=link[name=\"Close\"]";
    private final String button = "role=button";
    private final String reset = "role=button[name=\"Reset\"]";
    private final String submit = "role=button[name=\"Submit\"]";
    private final String filters = "role=link[name=\"Filters\"]";
    private final String favourite = "role=link[name=\"Favourite\"]";
    private final String nifty_strategies_basket_v2 = "role=link[name=\"NIFTY Strategies Basket V2\"]";
    private final String read_more = "role=link[name=\"Read more\"]";
    private final String patni_capital_pvt_lt = "role=link[name=\"Patni Capital PVT LTD\"]";
    private final String nfo = "role=link[name=\"NFO\"]";
    private final String pairs = "role=link[name=\"Pairs \"]";
    private final String bullish = "role=link[name=\"Bullish\"]";
    private final String bearish = "role=link[name=\"Bearish\"]";
    private final String directional = "role=link[name=\"Directional\"]";
    private final String positional = "role=link[name=\"Positional\"]";
    private final String subscribe = "role=link[name=\"Subscribe\"]";
    private final String nifty_directional_op = "role=link[name=\"NIFTY Directional Option Selling With Hedge V1\"]";
    private final String ms_wealth_booster = "role=link[name=\"MS Wealth Booster\"]";
    private final String ms___moneysuccess = "role=link[name=\"MS - MoneySuccess\"]";
    private final String shortvol = "role=link[name=\"ShortVol\"]";
    private final String nondirectional = "role=link[name=\"NonDirectional\"]";
    private final String range = "role=link[name=\"Range\"]";private final String 1 m_nifty_50_buy_520_="role=link[name=\"1M NIFTY 50 BUY 520 741 777 8\"]";
    private final String ishani_alogs = "role=link[name=\"ISHANI ALOGs\"]";
    private final String momentum = "role=link[name=\"Momentum\"]";
    private final String breakout = "role=link[name=\"Breakout \"]";
    private final String option_buying = "role=link[name=\"Option Buying\"]";
    private final String nifty_strategies_basket_v3 = "role=link[name=\"NIFTY Strategies Basket V3\"]";
    private final String premium_nifty_basket = "role=link[name=\"Premium Nifty Basket Type 1\"]";
    private final String algoguru = "role=link[name=\"AlgoGuru\"]";
    private final String earntheta = "role=link[name=\"EarnTheta\"]";
    private final String option_selling = "role=link[name=\"Option Selling\"]";
    private final String intraday = "role=link[name=\"Intraday\"]";
    private final String banknifty_monthly_wi = "role=link[name=\"BANKNIFTY Monthly with Directional\"]";
    private final String crypto_btc_options_s = "role=link[name=\"Crypto BTC Options Selling: Premium Decay Strategy\"]";
    private final String algo_pro_universe = "role=link[name=\"Algo Pro Universe\"]";
    private final String deltaindia = "role=link[name=\"DELTAINDIA\"]";
    private final String marketneutral = "role=link[name=\"MarketNeutral\"]";
    private final String expiry_trading = "role=link[name=\"Expiry Trading\"]";
    private final String part_3_booster_far_o = "role=link[name=\"part 3 Booster far otm hedge\"]";
    private final String ezee_trading = "role=link[name=\"Ezee Trading\"]";
    private final String bfo = "role=link[name=\"BFO\"]";
    private final String navigator_nifty_opti = "role=link[name=\"NAVIGATOR NIFTY OPTION BUYING\"]";
    private final String read_more___ = "role=link[name=\"Read More...\"]";
    private final String ramesh_intraalgo = "role=link[name=\"Ramesh IntraAlgo\"]";
    private final String bitcoin_call_sell = "role=link[name=\"Bitcoin call sell\"]";
    private final String just_one_trade = "role=link[name=\"JUST ONE TRADE\"]";
    private final String scalping = "role=link[name=\"Scalping\"]";
    private final String dr_algo_5_in_1_multi = "role=link[name=\"Dr Algo 5 in 1 Multi Index Option Buy Strategy\"]";
    private final String doctor_algo = "role=link[name=\"Doctor Algo\"]";
    private final String news = "role=link[name=\"News\"]";
    private final String supportresistance = "role=link[name=\"SupportResistance\"]";
    private final String trendfollowing = "role=link[name=\"TrendFollowing\"]";
    private final String swing = "role=link[name=\"Swing \"]";
    private final String bnf_pro_scalper_2_0_ = "role=link[name=\"BNF PRO SCALPER 2.0 ,read descriptions\"]";
    private final String harsh_gupta = "role=link[name=\"Harsh Gupta\"]";
    private final String genius_sminvist = "role=link[name=\"GENIUS SMINVIST\"]";
    private final String genius_algo_system = "role=link[name=\"Genius algo system\"]";
    private final String send_request = "role=link[name=\"Send Request\"]";
    private final String pk_nifty_buying_stra = "role=link[name=\"PK NIFTY BUYING STRATEGY\"]";
    private final String gpk_algo_trading = "role=link[name=\"GPK ALGO TRADING\"]";private final String 2="role=link[name=\"2\"]";private final String 3="role=link[name=\"3\"]";private final String 4="role=link[name=\"4\"]";private final String 5="role=link[name=\"5\"]";private final String 6="role=link[name=\"6\"]";private final String 7="role=link[name=\"7\"]";private final String 8="role=link[name=\"8\"]";private final String 57="role=link[name=\"57\"]";private final String 58="role=link[name=\"58\"]";
    private final String _ = "role=link[name=\"Next »\"]";
    private final String purchase_plan = "role=button[name=\"Purchase plan\"]";
    private final String proceed = "role=button[name=\"Proceed\"]";
    private final String go_to_my_strategies = "role=button[name=\"Go to My Strategies\"]";
    private final String close_button = "role=button[name=\"Close\"]";
    private final String forgot_password_ = "role=link[name=\"Forgot password?\"]";
    private final String visit_altcha_org = "role=link[name=\"Visit Altcha.org\"]";
    private final String sign_in_button = "role=button[name=\"Sign in\"]";
    private final String sign_in_with_faceboo = "role=link[name=\"Sign in with Facebook\"]";
    private final String sign_in_with_google = "role=link[name=\"Sign in with Google\"]";
    private final String terms_of_service_link = "role=link[name=\"terms of service\"]";
    private final String sign_up_button = "role=button[name=\"Sign up\"]";
    private final String sign________________ = "role=link[name=\"Sign
                                in\"]";
    private final String tour = "role=button[name=\"TOUR\"]";private final String 080471_89100="role=link[name=\"080471 89100\"]";
    private final String contact_tradetron_te = "role=link[name=\"contact@tradetron.tech\"]";
    private final String facebook = "role=link[name=\"facebook\"]";
    private final String twitter = "role=link[name=\"twitter\"]";
    private final String linkedin = "role=link[name=\"linkedin\"]";
    private final String youtube = "role=link[name=\"Youtube\"]";
    private final String features_link = "role=link[name=\"Features\"]";
    private final String wall_of_love = "role=link[name=\"Wall of Love\"]";
    private final String api = "role=link[name=\"API\"]";
    private final String affiliates = "role=link[name=\"Affiliates\"]";
    private final String coupon_sellers = "role=link[name=\"Coupon sellers\"]";
    private final String integrations = "role=link[name=\"Integrations\"]";
    private final String resources = "role=link[name=\"Resources\"]";
    private final String blog = "role=link[name=\"Blog\"]";
    private final String helpdesk = "role=link[name=\"Helpdesk\"]";
    private final String backtest = "role=link[name=\"Backtest\"]";
    private final String paper_trading = "role=link[name=\"PaperTrading\"]";
    private final String option_wizard = "role=link[name=\"OptionWizard\"]";
    private final String stockbag_link = "role=link[name=\"StockBag\"]";
    private final String straddle_strategy = "role=link[name=\"StraddleStrategy\"]";
    private final String videos = "role=link[name=\"Videos\"]";
    private final String strategy_templates = "role=link[name=\"Strategy Templates\"]";
    private final String keyword_documentatio = "role=link[name=\"Keyword Documentation\"]";
    private final String faq = "role=link[name=\"FAQ\"]";
    private final String top_creators = "role=link[name=\"Top Creators\"]";
    private final String qna_forum = "role=link[name=\"QnA Forum\"]";
    private final String tt_status = "role=link[name=\"TT Status\"]";
    private final String privacy_policy = "role=link[name=\"Privacy Policy\"]";
    private final String terms_of_use = "role=link[name=\"Terms of use\"]";
    private final String trademark = "role=link[name=\"Trademark\"]";
    private final String careers = "role=link[name=\"Careers\"]";

    public TradetronPage(Page page) {
        super(page);
    }

    public void search(String query) {
        this.fill(this.searchstring_input, query);
        this.pressKey(this.searchstring_input, "Enter");
    }
}